---
version: "3"
services:
  movie:
    image: suryashankar598/phonepaymovie:latest
    ports:
      - 8000:80
    deploy:
      replicas: 5
  train:
    image: suryashankar598/phonepaytrainticket:latest
    ports:
      - 8001:80
    deploy:
      replicas: 5
  loan:
    image: suryashankar598/phonepayloanpayment:latest
    ports:
      - 8002:80
    deploy:
      replicas: 5
  flight:
    image: suryashankar598/phonepayflighttickets:latest
    ports:
      - 8003:80
    deploy:
      replicas: 5
